import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import ToasterProvider from "@/components/ToasterProvider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased bg-gray-50 dark:bg-gray-800 dark:text-gray-100 text-gray-900">
        <ThemeProvider>
          <SessionProvider>
            <ToasterProvider />
            <Navbar />
            <main className="max-w-7xl mx-auto p-6">{children}</main>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
